
// -----------------------------------------------------------------------------
// @file fnn_layout.h
//
// @date April, 2025
//
// @author Generated by generate_fnn_layout.py
// -----------------------------------------------------------------------------

#ifndef FNN_LAYOUT_H
#define FNN_LAYOUT_H

#include <g_page.h>

#define SIZEOF(x) ((int)(sizeof(x) / sizeof(x[0])))

#ifdef __cplusplus
extern "C" {
#endif

extern g_page_t page[3];
extern float    OUT_YT[10];

void fnn_layout_to_pages(void);
#ifdef __cplusplus
}
#endif

#endif // FNN_LAYOUT_H

// -----------------------------------------------------------------------------
// End of File
