
// -----------------------------------------------------------------------------
// @file fnn_layout.c
//
// @date April, 2025
//
// @author Generated by generate_fnn_layout.py
// -----------------------------------------------------------------------------

#include "fnn_layout.h"

// layer 0: input layer
float L00_Y[7] = {0.0f};

// layer 1: hidden layer
float             L01_W[20][8]   = {{0.0f}};
float             L01_Z[20]      = {0.0f};
float             L01_Y[20]      = {0.0f};
float             L01_dY_dZ[20]  = {0.0f};
float             L01_dE_dY[20]  = {0.0f};
float             L01_LR         = 0.01f;
g_act_func_type_t L01_AF_TYPE    = LEAKY_RELU;
float             L01_AF_ARGS[1] = {0.01f};

// layer 2: hidden layer
float             L02_W[20][21]  = {{0.0f}};
float             L02_Z[20]      = {0.0f};
float             L02_Y[20]      = {0.0f};
float             L02_dY_dZ[20]  = {0.0f};
float             L02_dE_dY[20]  = {0.0f};
float             L02_LR         = 0.02f;
g_act_func_type_t L02_AF_TYPE    = LEAKY_RELU;
float             L02_AF_ARGS[1] = {0.01f};

// layer 3: output layer
float             L03_W[10][21]  = {{0.0f}};
float             L03_Z[10]      = {0.0f};
float             L03_Y[10]      = {0.0f};
float             L03_dY_dZ[10]  = {0.0f};
float             L03_dE_dY[10]  = {0.0f};
float             L03_LR         = 0.03f;
g_act_func_type_t L03_AF_TYPE    = SIGMOID;
float             L03_AF_ARGS[1] = {0.0f};

// layer 3: actual outputs (Y target)
float OUT_YT[10] = {0.0f};

g_page_t page[3];

void fnn_layout_to_pages(void) {
    // Layer 1
    page[0].l_id        = 0;
    page[0].x.ptr       = L00_Y;
    page[0].x.len       = SIZEOF(L00_Y);
    page[0].w.ptr       = (float *)L01_W;
    page[0].w.row       = SIZEOF(L01_W);
    page[0].w.col       = SIZEOF(L01_W[0]);
    page[0].z.ptr       = L01_Z;
    page[0].z.len       = SIZEOF(L01_Z);
    page[0].y.ptr       = L01_Y;
    page[0].y.len       = SIZEOF(L01_Y);
    page[0].dy_dz.ptr   = L01_dY_dZ;
    page[0].dy_dz.len   = SIZEOF(L01_dY_dZ);
    page[0].de_dy.ptr   = L01_dE_dY;
    page[0].de_dy.len   = SIZEOF(L01_dE_dY);
    page[0].lr          = L01_LR;
    page[0].af_type     = L01_AF_TYPE;
    page[0].af_args.ptr = L01_AF_ARGS;
    page[0].af_args.len = SIZEOF(L01_AF_ARGS);
    // Layer 2
    page[1].l_id        = 1;
    page[1].x.ptr       = L01_Y;
    page[1].x.len       = SIZEOF(L01_Y);
    page[1].w.ptr       = (float *)L02_W;
    page[1].w.row       = SIZEOF(L02_W);
    page[1].w.col       = SIZEOF(L02_W[0]);
    page[1].z.ptr       = L02_Z;
    page[1].z.len       = SIZEOF(L02_Z);
    page[1].y.ptr       = L02_Y;
    page[1].y.len       = SIZEOF(L02_Y);
    page[1].dy_dz.ptr   = L02_dY_dZ;
    page[1].dy_dz.len   = SIZEOF(L02_dY_dZ);
    page[1].de_dy.ptr   = L02_dE_dY;
    page[1].de_dy.len   = SIZEOF(L02_dE_dY);
    page[1].lr          = L02_LR;
    page[1].af_type     = L02_AF_TYPE;
    page[1].af_args.ptr = L02_AF_ARGS;
    page[1].af_args.len = SIZEOF(L02_AF_ARGS);
    // Layer 3
    page[2].l_id        = 2;
    page[2].x.ptr       = L02_Y;
    page[2].x.len       = SIZEOF(L02_Y);
    page[2].w.ptr       = (float *)L03_W;
    page[2].w.row       = SIZEOF(L03_W);
    page[2].w.col       = SIZEOF(L03_W[0]);
    page[2].z.ptr       = L03_Z;
    page[2].z.len       = SIZEOF(L03_Z);
    page[2].y.ptr       = L03_Y;
    page[2].y.len       = SIZEOF(L03_Y);
    page[2].dy_dz.ptr   = L03_dY_dZ;
    page[2].dy_dz.len   = SIZEOF(L03_dY_dZ);
    page[2].de_dy.ptr   = L03_dE_dY;
    page[2].de_dy.len   = SIZEOF(L03_dE_dY);
    page[2].lr          = L03_LR;
    page[2].af_type     = L03_AF_TYPE;
    page[2].af_args.ptr = L03_AF_ARGS;
    page[2].af_args.len = SIZEOF(L03_AF_ARGS);
}

// -----------------------------------------------------------------------------
// End of File
